use std::{cell::RefCell, collections::HashSet, rc::Rc};
#[derive(Clone)]pub struct Value(Rc<RefCell<Node>>);
#[derive(Clone)]enum Op{Leaf,Add(Value,Value),Mul(Value,Value),MatMul(Value,Value),Transpose(Value),Log(Value),Neg(Value),Softmax(Value),Relu(Value),ConcatRows(Vec<Value>),ConcatCols(Vec<Value>),Gather(Value,usize)}
struct Node{r:usize,c:usize,d:Vec<f32>,g:Vec<f32>,op:Op}
impl Value{
 fn mk(r:usize,c:usize,d:Vec<f32>,op:Op)->Self{assert_eq!(r*c,d.len());Self(Rc::new(RefCell::new(Node{r,c,g:vec![0.;d.len()],d,op})))}
 pub fn leaf(r:usize,c:usize,d:Vec<f32>)->Self{Self::mk(r,c,d,Op::Leaf)}
 pub fn parameter(r:usize,c:usize,s:&mut u64)->Self{let mut d=Vec::with_capacity(r*c);for _ in 0..r*c{*s=s.wrapping_mul(6364136223846793005).wrapping_add(1);let u=((*s>>32)as u32)as f32/u32::MAX as f32;d.push((u-.5)*.05);}Self::leaf(r,c,d)}
 pub fn data(&self)->Vec<f32>{self.0.borrow().d.clone()}pub fn grad(&self)->Vec<f32>{self.0.borrow().g.clone()}pub fn shape(&self)->(usize,usize){let n=self.0.borrow();(n.r,n.c)}pub fn zero_grad(&self){self.0.borrow_mut().g.fill(0.)}pub fn set_data(&self,d:Vec<f32>){assert_eq!(d.len(),self.0.borrow().d.len());self.0.borrow_mut().d=d}
 pub fn add(&self,b:&Self)->Self{let x=self.data();let y=b.data();assert_eq!(x.len(),y.len());Self::mk(self.shape().0,self.shape().1,x.iter().zip(y).map(|(a,b)|a+b).collect(),Op::Add(self.clone(),b.clone()))}
 pub fn mul(&self,b:&Self)->Self{let x=self.data();let y=b.data();assert_eq!(x.len(),y.len());Self::mk(self.shape().0,self.shape().1,x.iter().zip(y).map(|(a,b)|a*b).collect(),Op::Mul(self.clone(),b.clone()))}
 pub fn scalar_mul(&self,s:f32)->Self{self.mul(&Self::leaf(self.shape().0,self.shape().1,vec![s;self.0.borrow().d.len()]))}pub fn add_scalar(&self,s:f32)->Self{self.add(&Self::leaf(self.shape().0,self.shape().1,vec![s;self.0.borrow().d.len()]))}pub fn div_scalar(&self,s:f32)->Self{self.scalar_mul(1./s)}
 pub fn matmul(&self,b:&Self)->Self{let(ar,ac)=self.shape();let(br,bc)=b.shape();assert_eq!(ac,br);let x=self.data();let y=b.data();let mut o=vec![0.;ar*bc];for i in 0..ar{for k in 0..ac{let a=x[i*ac+k];for j in 0..bc{o[i*bc+j]+=a*y[k*bc+j]}}}Self::mk(ar,bc,o,Op::MatMul(self.clone(),b.clone()))}
 pub fn transpose(&self)->Self{let(r,c)=self.shape();let x=self.data();let mut o=vec![0.;r*c];for i in 0..r{for j in 0..c{o[j*r+i]=x[i*c+j]}}Self::mk(c,r,o,Op::Transpose(self.clone()))}
 pub fn log(&self)->Self{Self::mk(self.shape().0,self.shape().1,self.data().into_iter().map(|x|x.max(1e-20).ln()).collect(),Op::Log(self.clone()))}pub fn neg(&self)->Self{Self::mk(self.shape().0,self.shape().1,self.data().into_iter().map(|x|-x).collect(),Op::Neg(self.clone()))}
 pub fn relu(&self)->Self{Self::mk(self.shape().0,self.shape().1,self.data().into_iter().map(|x|x.max(0.)).collect(),Op::Relu(self.clone()))}
 pub fn softmax(&self)->Self{let(r,c)=self.shape();assert_eq!(r,1);let x=self.data();let m=x.iter().copied().fold(f32::NEG_INFINITY,f32::max);let e:Vec<f32>=x.iter().map(|v|(*v-m).exp()).collect();let z=e.iter().sum::<f32>().max(1e-20);Self::mk(1,c,e.into_iter().map(|v|v/z).collect(),Op::Softmax(self.clone()))}
 pub fn concat_rows(xs:&[Self])->Self{assert!(!xs.is_empty());let c=xs[0].shape().1;let mut d=Vec::new();for x in xs{assert_eq!(x.shape(),(1,c));d.extend(x.data())}Self::mk(xs.len(),c,d,Op::ConcatRows(xs.to_vec()))}
 pub fn concat_cols(xs:&[Self])->Self{assert!(!xs.is_empty());let r=xs[0].shape().0;let mut c=0;for x in xs{assert_eq!(x.shape().0,r);c+=x.shape().1}let mut o=vec![0.;r*c];let mut off=0;for x in xs{let w=x.shape().1;let d=x.data();for i in 0..r{for j in 0..w{o[i*c+off+j]=d[i*w+j]}}off+=w}Self::mk(r,c,o,Op::ConcatCols(xs.to_vec()))}
 pub fn gather(&self,i:usize)->Self{let(r,c)=self.shape();assert_eq!(r,1);assert!(i<c);Self::mk(1,1,vec![self.data()[i]],Op::Gather(self.clone(),i))}
 pub fn backward(&self){let mut t=Vec::new();let mut s=HashSet::new();topo(self,&mut s,&mut t);self.0.borrow_mut().g.fill(1.);for v in t.into_iter().rev(){back(&v)}}
}
fn topo(v:&Value,s:&mut HashSet<usize>,t:&mut Vec<Value>){let p=Rc::as_ptr(&v.0)as usize;if !s.insert(p){return}match v.0.borrow().op.clone(){Op::Leaf=>{},Op::Add(a,b)|Op::Mul(a,b)|Op::MatMul(a,b)=>{topo(&a,s,t);topo(&b,s,t)},Op::Transpose(a)|Op::Log(a)|Op::Neg(a)|Op::Softmax(a)|Op::Relu(a)|Op::Gather(a,_)=>topo(&a,s,t),Op::ConcatRows(xs)|Op::ConcatCols(xs)=>for x in xs{topo(&x,s,t)}}t.push(v.clone())}
fn ag(v:&Value,g:&[f32]){let mut n=v.0.borrow_mut();for(i,x)in g.iter().enumerate(){n.g[i]+=*x}}
fn back(v:&Value){let g=v.grad();match v.0.borrow().op.clone(){Op::Leaf=>{},Op::Add(a,b)=>{ag(&a,&g);ag(&b,&g)},Op::Mul(a,b)=>{let x=a.data();let y=b.data();ag(&a,&g.iter().zip(&y).map(|(q,z)|q*z).collect::<Vec<_>>());ag(&b,&g.iter().zip(&x).map(|(q,z)|q*z).collect::<Vec<_>>())},Op::MatMul(a,b)=>{let(ar,ac)=a.shape();let(_,bc)=b.shape();let x=a.data();let y=b.data();let mut ga=vec![0.;ar*ac];let mut gb=vec![0.;ac*bc];for i in 0..ar{for k in 0..ac{for j in 0..bc{let q=g[i*bc+j];ga[i*ac+k]+=q*y[k*bc+j];gb[k*bc+j]+=x[i*ac+k]*q}}}ag(&a,&ga);ag(&b,&gb)},Op::Transpose(a)=>{let(r,c)=v.shape();let mut q=vec![0.;g.len()];for i in 0..r{for j in 0..c{q[i*c+j]=g[j*r+i]}}ag(&a,&q)},Op::Log(a)=>{ag(&a,&g.iter().zip(a.data()).map(|(q,x)|q/x.max(1e-20)).collect::<Vec<_>>())},Op::Neg(a)=>ag(&a,&g.iter().map(|q|-q).collect::<Vec<_>>()),Op::Relu(a)=>{ag(&a,&g.iter().zip(a.data()).map(|(q,x)|if x>0.{*q}else{0.}).collect::<Vec<_>>())},Op::Softmax(a)=>{let y=v.data();let dot=g.iter().zip(&y).map(|(q,x)|q*x).sum::<f32>();ag(&a,&y.iter().zip(g).map(|(y,q)|y*(q-dot)).collect::<Vec<_>>())},Op::ConcatRows(xs)=>{let c=v.shape().1;for(i,x)in xs.iter().enumerate(){ag(x,&g[i*c..(i+1)*c])}},Op::ConcatCols(xs)=>{let mut off=0;for x in xs{let w=x.shape().1;ag(x,&g[off..off+w]);off+=w}},Op::Gather(a,i)=>{let mut q=vec![0.;a.data().len()];q[i]=g[0];ag(&a,&q)}}}
#[cfg(test)]mod tests{use super::*;#[test]fn matmul_backward(){let a=Value::leaf(1,2,vec![2.,3.]);let b=Value::leaf(2,1,vec![5.,7.]);let y=a.matmul(&b);y.backward();assert_eq!(a.grad(),vec![5.,7.]);assert_eq!(b.grad(),vec![2.,3.]);}}
